[tool.poetry]
name = "progect-10-1-14-3"
version = "0.1.0"
description = ""
authors = ["Ekaterina_Naumova <amega00@gmail.com>"]
readme = "README.md"
packages = [{include = "progect_10"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
